import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Fall Guys: Ultimate Knockout",
    desc: "a massively 60 multiplayer game",
    categoryName: ["arcade-and-puzzle"],
    vendor: "mediatonic",
    price: "49.99",
    discount: "0",
    isLatest: true,
    isTop: true,
    rating: 4.2,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094291/VISKart/capsule_616x353_hlinmv.jpg",
  },
  {
    _id: uuid(),
    title: "Minecraft",
    desc: "create anything you can imagine in your own world",
    categoryName: ["adventure", "arcade-and-puzzle", "simulation"],
    vendor: "mojang-studios",
    price: "34.99",
    discount: "0",
    isLatest: true,
    isTop: true,
    rating: 3.7,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094336/VISKart/images_jepzhy.jpg",
  },
  {
    _id: uuid(),
    title: "PUBG",
    desc: "loot weapons and supplies, and survive among 100 players",
    categoryName: ["adventure", "action", "simulation"],
    vendor: "tencent",
    price: "19.99",
    discount: "0",
    isLatest: true,
    isTop: true,
    rating: 4.7,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094389/VISKart/playerunknowns-battlegrounds-pc-game-steam-cover_yr87li.jpg",
  },
  {
    _id: uuid(),
    title: "Dying Light 2",
    desc: "fight for survival in a post-apocalyptic open world",
    categoryName: ["adventure", "action"],
    vendor: "techland",
    price: "99.99",
    discount: "0",
    isLatest: true,
    isTop: true,
    rating: 4.8,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094436/VISKart/dying-light-2-hero-lead_gljgcs.jpg",
  },
  {
    _id: uuid(),
    title: "Cricket 2007",
    desc: "enjoy the immersive cricketing action across platform",
    categoryName: ["sports"],
    vendor: "EA Sports",
    price: "99.99",
    discount: "40",
    isLatest: false,
    isTop: false,
    rating: 3.2,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094482/VISKart/Cricket07_outjgo.png",
  },
  {
    _id: uuid(),
    title: "Crazy Taxi",
    desc: "drive crazy to the city and earn the respect in your city",
    categoryName: ["racing", "arcade-and-puzzle"],
    vendor: "Dreamcast Games",
    price: "39.99",
    discount: "20",
    isLatest: false,
    isTop: false,
    rating: 2.2,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094536/VISKart/Crazy_Taxi_-_Catch_a_Ride_Coverart_kbn8wb.png",
  },
  {
    _id: uuid(),
    title: "NFS Most Wanted",
    desc: "strive to be the #1 racer by competing with the 15 most-wanted's of the city",
    categoryName: ["racing", "sports"],
    vendor: "EA Games",
    price: "99.99",
    discount: "50",
    isLatest: false,
    isTop: false,
    rating: 3.9,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094574/VISKart/Need_for_Speed_Most_Wanted_Box_Art_tz40ov.jpg",
  },
  {
    _id: uuid(),
    title: "Roadrash",
    desc: "ride your bike through the city and win the race to earn money and respect",
    categoryName: ["racing", "arcade-and-puzzle"],
    vendor: "EA Games",
    price: "49.99",
    discount: "30",
    isLatest: false,
    isTop: false,
    rating: 4.9,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094220/VISKart/roadrash_xpczz1.webp",
  },
  {
    _id: uuid(),
    title: "Fifa 07",
    desc: "enjoy the immersive football action with all the legends of this sport",
    categoryName: ["sports"],
    vendor: "EA Games",
    price: "99.99",
    discount: "10",
    isLatest: false,
    isTop: false,
    rating: 4.5,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094189/VISKart/fifa_07_a_qdldxb.jpg",
  },
  {
    _id: uuid(),
    title: "Total Overdose",
    desc: "destory the criminals of the city to retain your title of the supreme gangstar",
    categoryName: ["action", "adventure"],
    vendor: "Eidos Games",
    price: "49.99",
    discount: "25",
    isLatest: false,
    isTop: false,
    rating: 1.2,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094206/VISKart/tod_ipehfi.png",
  },
  {
    _id: uuid(),
    title: "Transport Fever 2",
    desc: "xyz",
    categoryName: ["racing", "simulation"],
    vendor: "xyz",
    price: "349.99",
    discount: "50",
    isLatest: true,
    isTop: false,
    rating: 2.2,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094172/VISKart/capsule_616x353_l3xpnw.jpg",
  },
  {
    _id: uuid(),
    title: "Resident Evil 3",
    desc: "xyz",
    categoryName: ["action", "adventure"],
    vendor: "xyz",
    price: "549.99",
    discount: "60",
    isLatest: true,
    isTop: false,
    rating: 4.3,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094163/VISKart/capsule_616x353_rctjdc.jpg",
  },
  {
    _id: uuid(),
    title: "Spades",
    desc: "xyz",
    categoryName: ["arcade-and-puzzle"],
    vendor: "xyz",
    price: "79.99",
    discount: "5",
    isLatest: true,
    isTop: false,
    rating: 0.8,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094036/VISKart/capsule_616x353_kybja2.jpg",
  },
  {
    _id: uuid(),
    title: "F1 2021",
    desc: "xyz",
    categoryName: ["racing", "sports"],
    vendor: "EA Sports",
    price: "999.99",
    discount: "20",
    isLatest: true,
    isTop: false,
    rating: 3.2,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094027/VISKart/capsule_616x353_nkttpz.jpg",
  },
  {
    _id: uuid(),
    title: "Sid Meier's Civilization VI : Platinum Edition",
    desc: "xyz",
    categoryName: ["simulation", "adventure"],
    vendor: "xyz",
    price: "249.99",
    discount: "25",
    isLatest: true,
    isTop: false,
    rating: 4.1,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094017/VISKart/capsule_616x353_gmhfaj.jpg",
  },
  {
    _id: uuid(),
    title: "Sea of Thieves",
    desc: "xyz",
    categoryName: ["action", "adventure"],
    vendor: "xyz",
    price: "749.99",
    discount: "50",
    isLatest: true,
    isTop: false,
    rating: 4.7,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649094008/VISKart/capsule_616x353_bem2o8.jpg",
  },
  {
    _id: uuid(),
    title: "Football Manager 2021",
    desc: "xyz",
    categoryName: ["sports"],
    vendor: "xyz",
    price: "149.99",
    discount: "30",
    isLatest: true,
    isTop: false,
    rating: 3.6,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649093988/VISKart/capsule_616x353_imiyrb.jpg",
  },
  {
    _id: uuid(),
    title: "Horatio Goes Snowboarding",
    desc: "xyz",
    categoryName: ["sports", "adventure"],
    vendor: "xyz",
    price: "99.99",
    discount: "70",
    isLatest: true,
    isTop: false,
    rating: 2.5,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649093977/VISKart/capsule_616x353_j44kqt.jpg",
  },
  {
    _id: uuid(),
    title: "Brick Breaker Heart Collector",
    desc: "xyz",
    categoryName: ["arcade-and-puzzle"],
    vendor: "xyz",
    price: "29.99",
    discount: "5",
    isLatest: true,
    isTop: false,
    rating: 1.7,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649093966/VISKart/capsule_616x353_ediomh.jpg",
  },
  {
    _id: uuid(),
    title: "Soulpath: the final journey",
    desc: "xyz",
    categoryName: ["action", "adventure"],
    vendor: "xyz",
    price: "659.99",
    discount: "10",
    isLatest: true,
    isTop: false,
    rating: 0.4,
    imageSrc:
      "https://res.cloudinary.com/dbjdu0hvl/image/upload/v1649093892/VISKart/capsule_616x353_mfmevr.jpg",
  },
];
