const products = [
  {
    id: 0,
    title: "Fall Guys: Ultimate Knockout",
    desc: "a massively 60 multiplayer game",
    vendor: "",
    imageSrc: "/fallguys.png",
    price: "49.99",
    discount: "0",
    isNew: true,
    isTop: true,
  },
  {
    id: 1,
    title: "Minecraft",
    desc: "create anything you can imagine in your own world",
    vendor: "",
    imageSrc: "/minecraft.png",
    price: "34.99",
    discount: "0",
    isNew: true,
    isTop: true,
  },
  {
    id: 2,
    title: "PUBG",
    desc: "loot weapons and supplies, and survive among 100 players",
    vendor: "",
    imageSrc: "/pubg.png",
    price: "19.99",
    discount: "0",
    isNew: true,
    isTop: true,
  },
  {
    id: 3,
    title: "Dying Light 2",
    desc: "fight for survival in a post-apocalyptic open world",
    vendor: "",
    imageSrc: "/dyinglight2.jpg",
    price: "99.99",
    discount: "0",
    isNew: true,
    isTop: true,
  },
  {
    id: 4,
    title: "Cricket 2007",
    desc: "fight for survival in a post-apocalyptic open world",
    vendor: "EA Sports",
    imageSrc: "/cricket07.png",
    price: "99.99",
    discount: "40",
    isNew: false,
    isTop: false,
  },
  {
    id: 5,
    title: "Crazy Taxi",
    desc: "",
    vendor: "Dreamcast Games",
    imageSrc: "/crazytaxi.png",
    price: "39.99",
    discount: "20",
    isNew: false,
    isTop: false,
  },
  {
    id: 6,
    title: "NFS Most Wanted",
    desc: "",
    vendor: "EA Games",
    imageSrc: "/nfsmw.webp",
    price: "99.99",
    discount: "50",
    isNew: false,
    isTop: false,
  },
  {
    id: 7,
    title: "Roadrash",
    desc: "",
    vendor: "EA Games",
    imageSrc: "/roadrash.webp",
    price: "49.99",
    discount: "30",
    isNew: false,
    isTop: false,
  },
  {
    id: 12,
    title: "Fifa 07",
    desc: "",
    vendor: "EA Games",
    imageSrc: "/fifa07.jpg",
    price: "99.99",
    discount: "10",
    isNew: false,
    isTop: false,
  },
  {
    id: 8,
    title: "Total Overdose",
    desc: "",
    vendor: "Eidos Games",
    imageSrc: "/tod.png",
    price: "49.99",
    discount: "25",
    isNew: false,
    isTop: false,
  },
];

export { products };
